# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PokeCli < Formula
  desc "A CLI tool written in Go that allows you to view data about Pokémon from the terminal."
  homepage "https://github.com/digitalghost-dev/poke-cli"
  version "1.2.3"
  license "Apache License 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/digitalghost-dev/poke-cli/releases/download/v1.2.3/poke-cli_Darwin_x86_64.tar.gz"
      sha256 "a09ecb33acf1dd7c9ca64bd544bf9db2e5ed372c010da6a9c1a889ccbbbf3234"

      def install
        bin.install "poke-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/digitalghost-dev/poke-cli/releases/download/v1.2.3/poke-cli_Darwin_arm64.tar.gz"
      sha256 "accd412e53c3dd45de2ab05faab82ec4ec1df2437f7d548abd0204afe8862952"

      def install
        bin.install "poke-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/digitalghost-dev/poke-cli/releases/download/v1.2.3/poke-cli_Linux_x86_64.tar.gz"
      sha256 "aa928aa46ebd1fcde7c79e3fe9b639d2b3f1a8d0763972ea2044008a7a067d3b"
      def install
        bin.install "poke-cli"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/digitalghost-dev/poke-cli/releases/download/v1.2.3/poke-cli_Linux_arm64.tar.gz"
      sha256 "bdd5a36b73086b81d60716355db0abcc05c434ca50e01182d6190012ea66ce97"
      def install
        bin.install "poke-cli"
      end
    end
  end
end
