# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PokeCli < Formula
  desc "A CLI tool written in Go that allows you to view data about Pokémon from the terminal."
  homepage "https://github.com/digitalghost-dev/poke-cli"
  version "1.0.2-SNAPSHOT-8e10a6c"
  license "Apache License 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/digitalghost-dev/poke-cli/releases/download/v1.0.2/poke-cli_Darwin_x86_64.tar.gz"
      sha256 "7dd28bf53a25fa4152a6843faad50dda2c1a9239631356cf34ccfef27a47b8a2"

      def install
        bin.install "poke-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/digitalghost-dev/poke-cli/releases/download/v1.0.2/poke-cli_Darwin_arm64.tar.gz"
      sha256 "e09bc04006b662c44b646681c5820bb1a27df17b570e35d372f6a7eed99ecae8"

      def install
        bin.install "poke-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/digitalghost-dev/poke-cli/releases/download/v1.0.2/poke-cli_Linux_x86_64.tar.gz"
        sha256 "75d7b14c66b7264134743136e90ed6ce04eb233eccfd911e1775b986e0be41b5"

        def install
          bin.install "poke-cli"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/digitalghost-dev/poke-cli/releases/download/v1.0.2/poke-cli_Linux_arm64.tar.gz"
        sha256 "18bde2ebf8d32e07a4b4c47652114987835895bcfd5d5cffcf25b78ca826ecd1"

        def install
          bin.install "poke-cli"
        end
      end
    end
  end
end
