# This file was generated by GoReleaser. DO NOT EDIT.
cask "poke-cli" do
  name "poke-cli"
  desc "A hybrid CLI/TUI tool written in Go for viewing Pokémon data from the terminal!"
  homepage "https://docs.poke-cli.com/"
  version "1.8.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "poke-cli"

  on_macos do
    on_intel do
      url "https://github.com/digitalghost-dev/poke-cli/releases/download/v#{version}/poke-cli_Darwin_x86_64.zip"
      sha256 "ccc81d60c524c559830b751ca46287176b43b1336ceee574e7eb783b4a47d1d2"
    end
    on_arm do
      url "https://github.com/digitalghost-dev/poke-cli/releases/download/v#{version}/poke-cli_Darwin_arm64.zip"
      sha256 "b3f558b3f7c93489d237f4ca6d40c2f9ca34b94a14c6e2f092fd38f62c5b3d90"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/digitalghost-dev/poke-cli/releases/download/v#{version}/poke-cli_Linux_x86_64.zip"
      sha256 "2a71049d8a0cc06d01da41346804b20b8690ec787f9852dbde00e1f53f3d8358"
    end
    on_arm do
      url "https://github.com/digitalghost-dev/poke-cli/releases/download/v#{version}/poke-cli_Linux_arm64.zip"
      sha256 "b79e01b4850e020330628966d3494d256e77353c330db1f31fbaf5945480589d"
    end
  end

  postflight do
    if OS.mac? && system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/poke-cli"]
    end
  end

  # No zap stanza required
end
