# This file was generated by GoReleaser. DO NOT EDIT.
cask "poke-cli" do
  name "poke-cli"
  desc "A hybrid CLI/TUI tool written in Go for viewing Pokémon data from the terminal!"
  homepage "https://docs.poke-cli.com/"
  version "1.8.9"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "poke-cli"

  on_macos do
    on_intel do
      url "https://github.com/digitalghost-dev/poke-cli/releases/download/v#{version}/poke-cli_Darwin_x86_64.zip"
      sha256 "b890f570de253f47fb60e78b1165b70dc2975f34a8cd267631ba7d14e70f28bc"
    end
    on_arm do
      url "https://github.com/digitalghost-dev/poke-cli/releases/download/v#{version}/poke-cli_Darwin_arm64.zip"
      sha256 "5b6f4ae67c99e285d0def68545cab1f94ca702a1877cbcd0e629bf5d7ae01fd6"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/digitalghost-dev/poke-cli/releases/download/v#{version}/poke-cli_Linux_x86_64.zip"
      sha256 "10b8c33b2736ac46d31da8e994db669f03ff9308cb92df68d839c670576db700"
    end
    on_arm do
      url "https://github.com/digitalghost-dev/poke-cli/releases/download/v#{version}/poke-cli_Linux_arm64.zip"
      sha256 "82445ad51e5d0cc4e3a17063e77fd68e63f8c6534684bdaedefaf4cf1a4d9600"
    end
  end

  postflight do
    if OS.mac? && system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/poke-cli"]
    end
  end

  # No zap stanza required
end
