# This file was generated by GoReleaser. DO NOT EDIT.
cask "poke-cli" do
  name "poke-cli"
  desc "A hybrid CLI/TUI tool written in Go for viewing Pokémon data from the terminal!"
  homepage "https://docs.poke-cli.com/"
  version "1.8.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "poke-cli"

  on_macos do
    on_intel do
      url "https://github.com/digitalghost-dev/poke-cli/releases/download/v#{version}/poke-cli_Darwin_x86_64.zip"
      sha256 "892a14ed34c3e80bff7b0dd3ca7e3f58ef0a3c5490d5311294341c98538d5425"
    end
    on_arm do
      url "https://github.com/digitalghost-dev/poke-cli/releases/download/v#{version}/poke-cli_Darwin_arm64.zip"
      sha256 "5db9d8bb28a924437ef2309ebbf081a019a786cd3f84a0f343a3f5d64905fa9c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/digitalghost-dev/poke-cli/releases/download/v#{version}/poke-cli_Linux_x86_64.zip"
      sha256 "d8830bbb235c6c87a58c81f6470e1c2d119ff83bb38a0cb8e1431d215ce9b4dd"
    end
    on_arm do
      url "https://github.com/digitalghost-dev/poke-cli/releases/download/v#{version}/poke-cli_Linux_arm64.zip"
      sha256 "d0ff695847269e58f56d3cf49e877327a7d457d874f4c9e9a26d0c59911e0688"
    end
  end

  postflight do
    if OS.mac? && system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/poke-cli"]
    end
  end

  # No zap stanza required
end
